name: build and push a docker image to dockerhub
on:
  push: 
    branch:
      - main

env:
  IMAGE_NAME: latest
  DOCKERHUB_REPOSITORY: januolam/build_image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build the docker image
        run: docker build -t $IMAGE_NAME .
      - name: tag the docker image
        run: docker tag $IMAGE_NAME $DOCKERHUB_REPOSITORY:$IMAGE_NAME
      - name: push to dockerhub
        run: docker push $DOCKERHUB_REPOSITORY:$IMAGE_NAME

